project:
  type: website

website:
  title: "Hacktoberfest 2024"
  #google-analytics: "G-XXXXXXXXXX"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    site-url: https://kevinrue.github.io/hacktoberfest2024
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
